# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHp4imfi06rZa-qsehoPkBsrjcNI5IKj
"""

import pandas as pd

titanic_url = 'https://raw.githubusercontent.com/gptix/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv'
titanic_df = pd.read_csv(titanic_url)
titanic_df['Name'] = titanic_df['Name'].str.replace(r"[\"\',]", '')


# creating a connection
import sqlite3
sl_conn = sqlite3.connect('titanic_df')
sl_curs = sl_conn.cursor()

titanic_df.to_sql('titanic', con=sl_conn, if_exists='replace')

query = '''SELECT * FROM titanic;'''
test2 = sl_curs.execute(query).fetchall()

for i in test2:

    create_titanic_table = """
        CREATE TABLE titanic_two (
        Survived INT,
        Pclass INT,
        Name VARCHAR(200),
        SEX VARCHAR(30),
        AGE INT,
        Siblings_Spouses_Aboard INT,
        Parents_Children_Aboard INT,
        Fare INT
        );
    """
#sl_curs.execute(create_titanic_table)




import psycopg2
dbname = 'yiwtoxhe'
user = 'yiwtoxhe'
password = 'N6v47hh8c62hrCx4IrfIPXUay3BMCGjn'  # Don't commit or share this for security purposes!
host = 'rajje.db.elephantsql.com'  # Port should be included or default
pg_conn = psycopg2.connect(dbname=dbname, user=user,
                           password=password, host=host)
pg_curs = pg_conn.cursor()

pg_conn.close()
pg_conn = psycopg2.connect(dbname=dbname, user=user,
                           password=password, host=host)
pg_curs = pg_conn.cursor()

pg_curs.execute(create_titanic_table)

query = '''SELECT * FROM titanic_two'''
pg_curs.execute(query)
pg_curs.fetchall()

for i in test2:
    insert_var = '''
    INSERT INTO titanic_two
    (Survived, Pclass, Name, Sex, Age, Siblings_Spouses_Aboard, Parents_Children_Aboard, Fare)
    VALUES ''' + str(i[1:]) + ';'
    pg_curs.execute(insert_var)

query = "SELECT * FROM titanic_two;"

pg_curs.execute(query)
pg_curs.fetchall()

pg_conn.commit()
